-- Історія обробки замовлень: статуси, оплата та доставка.
-- Безпечно запускати один раз після commerce-upgrade.sql.

create table if not exists public.order_events (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  event_type text not null check (event_type in ('status', 'operations')),
  previous_value text,
  next_value text not null,
  summary text not null,
  actor_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists order_events_order_created_idx
  on public.order_events(order_id, created_at desc);

alter table public.order_events enable row level security;

drop policy if exists "admins read order events" on public.order_events;
drop policy if exists "admins add order events" on public.order_events;

create policy "admins read order events"
  on public.order_events for select to authenticated
  using (public.is_admin());

create policy "admins add order events"
  on public.order_events for insert to authenticated
  with check (public.is_admin() and actor_id = auth.uid());
