-- Захист каталогу: товари не видаляються фізично, а зміни фіксуються в журналі.
-- Після запуску замість видалення використовуйте «Приховати» / архівування.

create table if not exists public.product_events (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  event_type text not null check (event_type in ('created', 'updated', 'visibility')),
  summary text not null,
  actor_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists product_events_product_created_idx
  on public.product_events(product_id, created_at desc);

alter table public.product_events enable row level security;

drop policy if exists "admins read product events" on public.product_events;
drop policy if exists "admins add product events" on public.product_events;

create policy "admins read product events"
  on public.product_events for select to authenticated
  using (public.is_admin());

create policy "admins add product events"
  on public.product_events for insert to authenticated
  with check (public.is_admin() and actor_id = auth.uid());

-- Пряме фізичне видалення товарів заборонене: для архіву використовуйте is_active = false.
revoke delete on table public.products from authenticated;
